#!/bin/bash

NAME=${1}
NAME=${NAME##*/}
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

GTL=`git rev-parse --show-toplevel`
SAVE=$(dirname `find ${GTL} -name ${NAME}`)

(cd $SAVE; /usr/bin/osascript ${DIR}/thumbscrew.scpt ${SAVE} ${NAME} 2>/dev/null)
cat -
