#!/bin/bash

NAME=${1}
[ -n "${THUMB_PATH}" ] || exit 1

GTL=`git rev-parse --show-toplevel`
[ -d "${GTL}/keynotes" ] || mkdir "${GTL}/keynotes"

/usr/bin/osascript ${THUMB_PATH}/thumbscrew.scpt ${GTL} ${NAME} 2>/dev/null
cat -
