#!/bin/bash

NAME=${1}

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

GTL=`git rev-parse --show-toplevel`
[ -d "${GTL}/keynotes" ] || mkdir "${GTL}/keynotes"

/usr/bin/osascript ${DIR}/thumbscrew.scpt ${GTL} ${NAME} 2>/dev/null
cat -
